updated to core24

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -8,10 +8,11 @@ issues: https://github.com/CaptainDario/DaKanji/issues
 source-code: https://github.com/CaptainDario/DaKanji
 
 confinement: strict
-base: core22
+base: core24
 grade: stable
-architectures:
-  - amd64
+platforms:
+  amd64:
+  arm64:
 assumes:
   - snapd2.60.3
 
@@ -38,7 +39,7 @@ parts:
 
   flutter-git:
     source: https://github.com/flutter/flutter.git
-    source-tag: "3.24.4"
+    source-tag: "3.29.1"
     plugin: nil
     override-build: |
       set -eux
@@ -79,17 +80,17 @@ parts:
 
   # Find files provided by the base and platform snap and ensure they aren't
   # duplicated in this snap
-  cleanup:
-    after: [dakanji]  # Make this part run last; list all your other parts here
-    plugin: nil
-    build-snaps: [gnome-42-2204]  # List all content-snaps you're using here
-    override-prime: |
-      set -eux
-      for snap in "gnome-42-2204"; do  # List all content-snaps you're using here
-        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
-      done
-      for CRUFT in bug lintian man; do
-        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
-      done
-      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
-      find $CRAFT_PRIME/usr/share -type d -empty -delete
+  #cleanup:
+  #  after: [dakanji]  # Make this part run last; list all your other parts here
+  #  plugin: nil
+  #  build-snaps: [gnome-42-2204]  # List all content-snaps you're using here
+  #  override-prime: |
+  #    set -eux
+  #    for snap in "gnome-42-2204"; do  # List all content-snaps you're using here
+  #      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
+  #    done
+  #    for CRUFT in bug lintian man; do
+  #      rm -rf $CRAFT_PRIME/usr/share/$CRUFT
+  #    done
+  #    find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
+  #    find $CRAFT_PRIME/usr/share -type d -empty -delete
